**24/12/2025**

- works best with `yes no` kind of problems
- Binomial - Deals with two classes, YES or NO
- multinomial - Deals with multiple classes

*refer image formula in sir's note*

- We are doing regression, in both cases
- trying to fit a line through the data

In the case above, data is modelled via straight line using: y = mx + c

*refer image formula in sir's note*

Data is modelled using a sigmoid function: y = sigmoid(x)

Model Logistic Regression:
- Learning Parameters: Co-efficients = weights and bias  =  w1* x1 + B
- Loss function: LOG-LOSS

### Try to understand somethings about CLASSIFICATION

**Exercise 1**

create label encoding for 'smoker' column

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learniing
from sklearn.linear_model import LinearRegression, LogisticRegression
# Model Training
from sklearn.model_selection import train_test_split
# Model Evaluation
from sklearn.metrics import mean_absolute_error, r2_score

In [2]:
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

- **Feature Engineering**: is legit
    - The classifier, logistic regression, will not accept, continous values.
    - we supply catagorical values

In [3]:
x = tips[['total_bill']]
y = tips['tip']

model = LinearRegression()

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=42, test_size=0.2)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f'r2: {r2} \nmae: {mae}')

r2: 0.5449381659234663
mae: 0.6208580000398983

In [ ]:
#SNAS: my answer below for Exercise 1

In [3]:
from sklearn.preprocessing import LabelEncoder

#create LabelEncoder instance
encoder = LabelEncoder()

tips['smoker_le'] = encoder.fit_transform(tips['smoker'])
tips

     total_bill   tip     sex smoker   day    time  size  smoker_le
0         16.99  1.01  Female     No   Sun  Dinner     2          0
1         10.34  1.66    Male     No   Sun  Dinner     3          0
2         21.01  3.50    Male     No   Sun  Dinner     3          0
3         23.68  3.31    Male     No   Sun  Dinner     2          0
4         24.59  3.61  Female     No   Sun  Dinner     4          0
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3          0
240       27.18  2.00  Female    Yes   Sat  Dinner     2          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2          1
242       17.82  1.75    Male     No   Sat  Dinner     2          0
243       18.78  3.00  Female     No  Thur  Dinner     2          0

[244 rows x 8 columns]

In [ ]:
# ---------------------------------------------
# sir answer as below

In [5]:
# simple, manual label encoding using map method
tips['smoker_bin'] = tips['smoker'].map({
    'Yes': 1,
    'No' : 0}
)

tips['sex_bin'] = tips['sex'].map({
    'Male': 1,
    'Female' : 0}
)

tips.head(2)

   total_bill   tip     sex smoker  day    time  size smoker_bin sex_bin
0       16.99  1.01  Female     No  Sun  Dinner     2          0       0
1       10.34  1.66    Male     No  Sun  Dinner     3          0       1

In [6]:
# X = tips[['smoker_bin']] # 0101011101110101
y = tips['tip'] # continous

# convert the target column, then use it for y

X = tips[['total_bill']] 
y = tips['sex_bin'] # encoded column

# yes, how much did they tip?
# are we predicting a continous value?

using this dataset, linear regression: 
- take a contious values
- predict a continous value

Logistic Regression
- classification algorithm
- tips(continous) vs smoker_bin (catagorical)

REGRESSION
- Are you trying to predict the tip amount (REGRESSION), based on if a person smokes or not?
- use smoker or not, to judge the amount of bill

CLASSIFICATION
- if a certain amount of tip, can we predict, if person is a smoker or not? (CLASSIFICATION)
- use bill to judge smoker or not

Failsafe for pushing alphbetic/non numeric data into the model
- if you accidentally, use a binary category for y, still be able to classify things
- it will do the label encoding internally, when doing the model fit

In [7]:
y_train

228    2.72
208    2.03
96     4.00
167    4.50
84     2.03
       ...
106    4.06
14     3.02
92     1.00
179    3.55
102    2.50
Name: tip, Length: 195, dtype: float64

In [ ]:
model_Logistic = LogisticRegression() # classification

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state= 42, test_size=0.2)

model_Logistic.fit(X_train, y_train) # fitting here, must be numeric

y_pred = model_Logistic.predict(X_test)

In [9]:
model_Logistic.predict([[i] for i in range(50)])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

**25/12/2025**

**Exercise 2**

In [ ]:
# Exercise using Titanic dataset to use logistic regression with X continous and Y the survival rate
#SNAS: my answer as below

In [10]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
sex_le           0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

#create LabelEncoder instance
encoder = LabelEncoder()

titanic['sex_le'] = encoder.fit_transform(titanic['sex'])
titanic

#SNAS: actually no need to encoded sex because not using this column to analyze

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_le
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [19]:
x = titanic[['fare']]  #SNAS: dropped age column as it contains lots of NaN value
y = titanic['survived']

In [20]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: survived, Length: 712, dtype: int64

In [21]:
model_logistic = LogisticRegression() # classification

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state= 42, test_size=0.2)

model_logistic.fit(x_train, y_train) # fitting here, must be numeric

y_pred = model_logistic.predict(x_test)

In [23]:
model_logistic.predict([[i] for i in range(50)])

c:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [ ]:
# ----------------------------------------

In [25]:
# evaluate performance
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# confusion matrix

accuracy_test = accuracy_score(y_test, y_pred)
accuracy_test

0.6536312849162011

In [26]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[100,   5],
       [ 57,  17]])

In [28]:
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.64      0.95      0.76       105
           1       0.77      0.23      0.35        74

    accuracy                           0.65       179
   macro avg       0.70      0.59      0.56       179
weighted avg       0.69      0.65      0.59       179