**02/12/2025**

In [ ]:
# let's try to bring in the csv file here

import pandas as pd

df = pd.read_csv("City Rating.csv")
df

   Unnamed: 0       city  temp10  new_temp  melRating  idreesRating
0           0         KL      23        40         -1             5
1           1         HK      29        34          5             3
2           2     London      40        20          4             3
3           3  Singapore       0        42          2             3
4           4      Tokyo       5        45          3             3

In [ ]:
df.drop('Unnamed: 0', axis=1)   # SNAS: to delete a column or row for table df (City Rating.csv)
#SNAS: axis = 0, remove row
#SNAS: axis = 1, remove column

In [ ]:
df2 = pd.read_csv("City Rating without Row Numbers.csv") #SNAS: read csv file which already created without the first column Unnamed:0e
df2

        city  temp10  new_temp  melRating  idreesRating
0         KL      23        40         -1             5
1         HK      29        34          5             3
2     London      40        20          4             3
3  Singapore       0        42          2             3
4      Tokyo       5        45          3             3

In [ ]:
df3 = pd.read_csv("grades.csv")
df3

      name  Idrees  Mel  Ibrahim
0    maths      96   95       94
1  english      96   95       94
2  science      96   95       94