**02/12/2025**

- Python
    -  variables - storing data
    - data types - *int float string* - string **list dictionary** set range
    - functions - create reusable code, lots of lines of code in one place
    - classes - help us containerise code, box things up

- Libraries
    - numpy - **arrays** we can create matrices, numerical calculation
    - pandas - **DataFrames** store data like spread sheet, excel sheets, we can manipulate those tables

- Machine Learning
    - data - clean data, analyse data, play with data
    - feed to the machine
    - show the machine what is right, what is wrong (learns, creates its own patterns)
    - then you ask questions, and get answers

Dictionaries

- we will try to create a dictionaries
- data types with keys and values

**Task 1**

In [ ]:
# create a small dictionary
# name of 4 students and their marks

#SNAS: my answer as below. there are better ways

student_record={'ID':1,'Name': 'Anjali','Marks':3.82,}
print(student_record)

student_record1={'ID':2,'Name': 'Ali','Marks':4.00,}
print(student_record1)

student_record2={'ID':3,'Name': 'Zack','Marks':2.90,}
print(student_record2)

student_record3={'ID':4,'Name': 'Ajay','Marks':3.95,}
print(student_record3)

print('Student Records')
for record in student_record.keys():
  print(record, '\t', student_record[record])

for record in student_record.keys():
  print(record, '\t', student_record1[record])

for record in student_record.keys():
  print(record, '\t', student_record2[record])

for record in student_record.keys():
  print(record, '\t', student_record3[record])

{'ID': 1, 'Name': 'Anjali', 'Marks': 3.82}
{'ID': 2, 'Name': 'Ali', 'Marks': 4.0}
{'ID': 3, 'Name': 'Zack', 'Marks': 2.9}
{'ID': 4, 'Name': 'Ajay', 'Marks': 3.95}
Student Records
ID 	 1
Name 	 Anjali
Marks 	 3.82
ID 	 2
Name 	 Ali
Marks 	 4.0
ID 	 3
Name 	 Zack
Marks 	 2.9
ID 	 4
Name 	 Ajay
Marks 	 3.95

In [13]:
student_record=[ 
    {'ID':1,'Name': 'Anjali', 'Marks':3.82},
    {'ID':2,'Name': 'Ali', 'Marks':4.00},
    {'ID':3,'Name': 'Zack', 'Marks':2.90},
    {'ID':4,'Name': 'Ajay', 'Marks':3.95}
    ]
#print(student_record)

for s in student_record:
    print(f"ID: {s['ID']}  Name: {s['Name']}  Marks: {s['Marks']}")

ID: 1  Name: Anjali  Marks: 3.82
ID: 2  Name: Ali  Marks: 4.0
ID: 3  Name: Zack  Marks: 2.9
ID: 4  Name: Ajay  Marks: 3.95

In [3]:
student_grades = {
'name' : ['Zie', 'Sam', 'Zack', 'Hazira', 'Amin', 'Nazri'],
'maths' : [90, 90, 80, 92, 94, 94],
'english' : [100, 75, 80, 92, 94, 98],
'science' : [40, 60, 90, 92, 94, 90],
}

print(student_grades)

{'name': ['Zie', 'Sam', 'Zack', 'Hazira', 'Amin', 'Nazri'], 'maths': [90, 90, 80, 92, 94, 94], 'english': [100, 75, 80, 92, 94, 98], 'science': [40, 60, 90, 92, 94, 90]}

In [4]:
student_grades['name']
student_grades['name'][2]

'Zack'

In [ ]:
# pip install pandas  #SNAS: syntax to install libraries. replace <panda> with library name

Collecting pandas
  Downloading pandas-2.3.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp314-cp314-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.1 MB 6.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/11.1 MB 7.4 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.1 MB 7.4 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.1 MB 7.6 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/11.1 MB 7.3 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.1 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 6.8 MB/s  0:00:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(student_grades)

df
print("\n first table ------------\n", df, "\n")
print("\n second table ------------\n", df, "\n")
print("\n third table ------------\n", df, "\n")

 first table ------------
      name  maths  english  science
0     Zie     90      100       40
1     Sam     90       75       60
2    Zack     80       80       90
3  Hazira     92       92       92
4    Amin     94       94       94
5   Nazri     94       98       90


 second table ------------
      name  maths  english  science
0     Zie     90      100       40
1     Sam     90       75       60
2    Zack     80       80       90
3  Hazira     92       92       92
4    Amin     94       94       94
5   Nazri     94       98       90


 third table ------------
      name  maths  english  science
0     Zie     90      100       40
1     Sam     90       75       60
2    Zack     80       80       90
3  Hazira     92       92       92
4    Amin     94       94       94
5   Nazri     94       98       90

In [14]:
type(df)
# numpy.ndarray

pandas.core.frame.DataFrame

In [ ]:
df.head()   # top part of a df is top 5 the default argument. if want to display specific quantity of rows, put number inside ()
            #SNAS: show only intended rows
df.tail()   # show last 5 row intended by default. if want to display specific quantity of rows, put number inside ()

     name  maths  english  science
1     Sam     90       75       60
2    Zack     80       80       90
3  Hazira     92       92       92
4    Amin     94       94       94
5   Nazri     94       98       90

In [7]:
# we can access data inside certain columns in dataframe too

df['maths'] #SNAS: it will show all data under 'maths' column

0    90
1    90
2    80
3    92
4    94
5    94
Name: maths, dtype: int64

In [8]:
# to refer sir video recording

print("\n Names columns ------\n", df['name'])
print("\n maths columns ------\n", df['maths'])  #SNAS:

 Names columns ------
 0       Zie
1       Sam
2      Zack
3    Hazira
4      Amin
5     Nazri
Name: name, dtype: object

 maths columns ------
 0    90
1    90
2    80
3    92
4    94
5    94
Name: maths, dtype: int64

In [10]:
import numpy as np

arrayyy = np.array([])
type(arrayyy)

numpy.ndarray

In [11]:
# series

marks_series = pd.Series([1,2,3])
# type(marks_series)

print(marks_series)

0    1
1    2
2    3
dtype: int64

In [12]:
# how many marks does amin have in english

print('Marks Amin for subject English is \t',df.english[4])

Marks Amin for subject English is 	 94

In [15]:
print(f'In English {df.name[2]} had {df.english[2]} marks')

In English Zack had 80 marks

In [ ]:
#SNAS: another way to write above statement. longer version

at = df["name"][2]
at_english = df["english"][2]

print(f"In English {at} has {at_english} marks")

In English Zack has 80 marks

In [19]:
haz = df["name"][3]
haz_maths = df["maths"][3]

print(f"In Maths {haz} has {haz_maths} marks")

In Maths Hazira has 92 marks

In [ ]:
# core data types we use in pandas?

# dataframe
# series

**Task 2**

Create a series of data using pd.series 5 values of temperature

dataframe city and temperature - 5 cities

In [55]:
#SNAS: my answer as below

temperature = {
'city' : ['Kuala Lumpur', 'Jakarta', 'London', 'Singapore', 'Tokyo'],
'celcius' : [23, 40, 28, 34, 16],
}

df = pd.DataFrame(temperature)

print(df)
#print(f"\n{df.city},{df.celcius}", "\n")

           city  celcius
0  Kuala Lumpur       23
1       Jakarta       40
2        London       28
3     Singapore       34
4         Tokyo       16

In [59]:
# sir answer as below
# series object - single columns, 3D columns

temp11 = pd.Series([32,31,50,34,-2])    #SNAS: temperature at Day 11
print("Type of temp11 is: ", type(temp11))

# a dictionary of temperatures
# python data object
temperatures = {
'city' : ['KL', 'HK', 'London', 'Singapore', 'Tokyo'],
'temp10' : [23, 29, 40, 0, 5],
}

# creating a datafram
# DataFrame is from panda
temp_df=pd.DataFrame(temperatures)
print("Type of temp_df is: ", type(temp_df))

print(temp_df)  #SNAS: temp_df is a dataframe
print(temp11)   #SNAS: temp11 is a series

Type of temp11 is:  <class 'pandas.core.series.Series'>
Type of temp_df is:  <class 'pandas.core.frame.DataFrame'>
        city  temp10
0         KL      23
1         HK      29
2     London      40
3  Singapore       0
4      Tokyo       5
0    32
1    31
2    50
3    34
4    -2
dtype: int64

In [53]:
df2 = temp_df   #SNAS: to create a separate copy of temp_df, because we don't want to change the value in temp_df
df2["temp11"] = temp11

df2["temp12"] = pd.Series([])

In [54]:
temp_df

        city  temp10  temp11 temp12
0         KL      23      32    NaN
1         HK      29      31    NaN
2     London      40      50    NaN
3  Singapore       0      34    NaN
4      Tokyo       5      -2    NaN

In [ ]:
# dataframe creates a column that does not exist
#SNAS: series & dictionary almost the same

#temp_df['city'] = {} #SNAS: to replace all elements in cities
#temp_df

temp_df["new_temp"] = pd.Series([]) #SNAS: the amount of elements should be the same to the series that we try to concatenate, but if not enough, value will be shown NaN
temp_df

  city  temp10 new_temp
0  NaN      23      NaN
1  NaN      29      NaN
2  NaN      40      NaN
3  NaN       0      NaN
4  NaN       5      NaN

In [ ]:
#SNAS: Exercise to insert new column with data into existing table

temp_df["new_temp"] = pd.Series([40, 34, 20, 42, 45]) #SNAS: to inser new data under new colum new_temp & append to the current table
temp_df #SNAS: panda able to display data series without using print

        city  temp10  new_temp
0         KL      23        40
1         HK      29        34
2     London      40        20
3  Singapore       0        42
4      Tokyo       5        45

In [62]:
temp_df["melRating"] = pd.Series([-1,5,4,2,3])
temp_df["idreesRating"] = pd.Series([5,3,3,3,3])
temp_df

        city  temp10  new_temp  melRating  idreesRating
0         KL      23        40         -1             5
1         HK      29        34          5             3
2     London      40        20          4             3
3  Singapore       0        42          2             3
4      Tokyo       5        45          3             3

In [ ]:
# above is already a dataset?
# save this as a csv file

temp_df.to_csv("City Rating.csv")    #SNAS: need to pass the name of the data. the document name in csv. put *.csv

temp_df.to_csv("City Rating without Row Numbers.csv", index=False) #SNAS: create csv without the first column Unnamed:0e of the data. the document name in csv. put *.csv

In [82]:
data = {
'cities' : ['KL', 'KL', 'HK', 'SG', 'NY', 'HLS'],
'temp10' : [23, 29, 29, 40, 0, 5],
}

df = pd.DataFrame(data)
df

  cities  temp10
0     KL      23
1     KL      29
2     HK      29
3     SG      40
4     NY       0
5    HLS       5

In [83]:
df['cities'].value_counts()

cities
KL     2
HK     1
SG     1
NY     1
HLS    1
Name: count, dtype: int64

In [ ]:
df['cities'].unique()   #SNAS: can run only on column

array(['KL', 'HK', 'SG', 'NY', 'HLS'], dtype=object)

In [ ]:
df['cities'].duplicated() #SNAS: return to you whether the value is being repeated or not. can run only on column

0    False
1     True
2    False
3    False
4    False
5    False
Name: cities, dtype: bool

In [85]:
df2=df['cities'].drop_duplicates()
df2

0     KL
2     HK
3     SG
4     NY
5    HLS
Name: cities, dtype: object