**03/12/2025**

**Task 1**

- import dataset
- run the methods we learnt value count, unique, on species column
- create a new df object, without the species column

In [21]:
import pandas as pd

In [22]:
iris_ds = pd.read_csv("iris.csv")

In [23]:
iris_ds

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [24]:
iris_ds['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [25]:
iris_ds['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [26]:
# create a new df object, without the species column

iris_without_species = iris_ds.drop('species', axis=1)

In [27]:
iris_without_species

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [28]:
iris_ds.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [29]:
species1 = iris_ds['species']
species1.head()

type(species1)

pandas.core.series.Series

In [30]:
# instead

species2 = iris_ds.drop(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], axis=1) #SNAS: <- this will not work because panda dataframe does not able to execute multiple variable. must use [] put in list
species2.head()

type(species2)

pandas.core.frame.DataFrame

In [31]:
# calculated column

sepalarea = iris_without_species['sepal_length'] #SNAS: dataframe only takes one argument. 

sepalarea = iris_without_species[['sepal_length', 'sepal_width']]   #SNAS: to take more argument, must put it in a list, then it will take it as a dataframe

sepalarea.head()

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6

In [32]:
sepalarea = iris_without_species['sepal_length'] * iris_without_species['sepal_width']  #SNAS: able to calculate all values between column

sepalarea.head()

0    17.85
1    14.70
2    15.04
3    14.26
4    18.00
dtype: float64

In [33]:
iris_without_species['sepal_area'] = sepalarea  #SNAS: able to display all the calculated values between column into a new column 'sepal_area'

iris_without_species.head()

   sepal_length  sepal_width  petal_length  petal_width  sepal_area
0           5.1          3.5           1.4          0.2       17.85
1           4.9          3.0           1.4          0.2       14.70
2           4.7          3.2           1.3          0.2       15.04
3           4.6          3.1           1.5          0.2       14.26
4           5.0          3.6           1.4          0.2       18.00

In [34]:
petalarea = iris_without_species['petal_length'] * iris_without_species['petal_width']
petalarea.head()

0    0.28
1    0.28
2    0.26
3    0.30
4    0.28
dtype: float64

In [35]:
iris_without_species['petal_area'] = petalarea
iris_without_species.head(50)

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
0,5.1,3.5,1.4,0.2,17.85,0.28
1,4.9,3.0,1.4,0.2,14.70,0.28
2,4.7,3.2,1.3,0.2,15.04,0.26
3,4.6,3.1,1.5,0.2,14.26,0.30
4,5.0,3.6,1.4,0.2,18.00,0.28
5,5.4,3.9,1.7,0.4,21.06,0.68
6,4.6,3.4,1.4,0.3,15.64,0.42
7,5.0,3.4,1.5,0.2,17.00,0.30
8,4.4,2.9,1.4,0.2,12.76,0.28
9,4.9,3.1,1.5,0.1,15.19,0.15
10,5.4,3.7,1.5,0.2,19.98,0.30
11,4.8,3.4,1.6,0.2,16.32,0.32
12,4.8,3.0,1.4,0.1,14.40,0.14
13,4.3,3.0,1.1,0.1,12.90,0.11
14,5.8,4.0,1.2,0.2,23.20,0.24
15,5.7,4.4,1.5,0.4,25.08,0.60
16,5.4,3.9,1.3,0.4,21.06,0.52
17,5.1,3.5,1.4,0.3,17.85,0.42
18,5.7,3.8,1.7,0.3,21.66,0.51
19,5.1,3.8,1.5,0.3,19.38,0.45
20,5.4,3.4,1.7,0.2,18.36,0.34
21,5.1,3.7,1.5,0.4,18.87,0.60
22,4.6,3.6,1.0,0.2,16.56,0.20
23,5.1,3.3,1.7,0.5,16.83,0.85
24,4.8,3.4,1.9,0.2,16.32,0.38
25,5.0,3.0,1.6,0.2,15.00,0.32
26,5.0,3.4,1.6,0.4,17.00,0.64
27,5.2,3.5,1.5,0.2,18.20,0.30
28,5.2,3.4,1.4,0.2,17.68,0.28
29,4.7,3.2,1.6,0.2,15.04,0.32
30,4.8,3.1,1.6,0.2,14.88,0.32
31,5.4,3.4,1.5,0.4,18.36,0.60
32,5.2,4.1,1.5,0.1,21.32,0.15
33,5.5,4.2,1.4,0.2,23.10,0.28
34,4.9,3.1,1.5,0.1,15.19,0.15
35,5.0,3.2,1.2,0.2,16.00,0.24
36,5.5,3.5,1.3,0.2,19.25,0.26
37,4.9,3.1,1.5,0.1,15.19,0.15
38,4.4,3.0,1.3,0.2,13.20,0.26
39,5.1,3.4,1.5,0.2,17.34,0.30
40,5.0,3.5,1.3,0.3,17.50,0.39
41,4.5,2.3,1.3,0.3,10.35,0.39
42,4.4,3.2,1.3,0.2,14.08,0.26
43,5.0,3.5,1.6,0.6,17.50,0.96
44,5.1,3.8,1.9,0.4,19.38,0.76
45,4.8,3.0,1.4,0.3,14.40,0.42
46,5.1,3.8,1.6,0.2,19.38,0.32
47,4.6,3.2,1.4,0.2,14.72,0.28
48,5.3,3.7,1.5,0.2,19.61,0.30
49,5.0,3.3,1.4,0.2,16.50,0.28

In [36]:
# filter out parts of dataframes using pandas
# only part of iris_without_species value of sepal_area is >14

largeFlowers = iris_without_species[iris_without_species['sepal_area'] > 15]    #SNAS: to filter within sepal_area column under iris_without_species dataframe
largeFlowers.head(10)

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
0,5.1,3.5,1.4,0.2,17.85,0.28
2,4.7,3.2,1.3,0.2,15.04,0.26
4,5.0,3.6,1.4,0.2,18.00,0.28
5,5.4,3.9,1.7,0.4,21.06,0.68
6,4.6,3.4,1.4,0.3,15.64,0.42
7,5.0,3.4,1.5,0.2,17.00,0.30
9,4.9,3.1,1.5,0.1,15.19,0.15
10,5.4,3.7,1.5,0.2,19.98,0.30
11,4.8,3.4,1.6,0.2,16.32,0.32
14,5.8,4.0,1.2,0.2,23.20,0.24

In [37]:
# how many large flowers we have in iris dataset
# how many flowers have a sepal area of exactly 16

largeFlowers = iris_without_species[iris_without_species['sepal_area'] > 15]
largeFlowers.info()

largeFlowers2 = iris_without_species[iris_without_species['sepal_area'] == 16]
largeFlowers2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  120 non-null    float64
 1   sepal_width   120 non-null    float64
 2   petal_length  120 non-null    float64
 3   petal_width   120 non-null    float64
 4   sepal_area    120 non-null    float64
 5   petal_area    120 non-null    float64
dtypes: float64(6)
memory usage: 6.6 KB
<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 35 to 35
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  1 non-null      float64
 1   sepal_width   1 non-null      float64
 2   petal_length  1 non-null      float64
 3   petal_width   1 non-null      float64
 4   sepal_area    1 non-null      float64
 5   petal_area    1 non-null      float64
dtypes: float64(6)
memory usage: 56.0 bytes

In [38]:
largeFlowers

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
0,5.1,3.5,1.4,0.2,17.85,0.28
2,4.7,3.2,1.3,0.2,15.04,0.26
4,5.0,3.6,1.4,0.2,18.00,0.28
5,5.4,3.9,1.7,0.4,21.06,0.68
6,4.6,3.4,1.4,0.3,15.64,0.42
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,20.10,11.96
146,6.3,2.5,5.0,1.9,15.75,9.50
147,6.5,3.0,5.2,2.0,19.50,10.40
148,6.2,3.4,5.4,2.3,21.08,12.42
149,5.9,3.0,5.1,1.8,17.70,9.18

In [ ]:
largeFlowers.to_csv('largeFlowers.csv') #SNAS: convert largeFlowers list into csv file

In [40]:
# sorting values by something

sortedLargeFlowers = largeFlowers.sort_values(by='sepal_area', ascending=False)
sortedLargeFlowers
# SNAS: above syntax to sort values via a column

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
131,7.9,3.8,6.4,2.0,30.02,12.80
117,7.7,3.8,6.7,2.2,29.26,14.74
109,7.2,3.6,6.1,2.5,25.92,15.25
15,5.7,4.4,1.5,0.4,25.08,0.60
14,5.8,4.0,1.2,0.2,23.20,0.24
...,...,...,...,...,...,...
34,4.9,3.1,1.5,0.1,15.19,0.15
94,5.6,2.7,4.2,1.3,15.12,5.46
92,5.8,2.6,4.0,1.2,15.08,4.80
2,4.7,3.2,1.3,0.2,15.04,0.26
29,4.7,3.2,1.6,0.2,15.04,0.32

In [41]:
largestFlower = sortedLargeFlowers['sepal_area']
largestFlower.head(1) #SNAS: only want to access and print the first value

131    30.02
Name: sepal_area, dtype: float64

In [42]:
sortedLargeFlowers = largeFlowers.sort_values(by='sepal_area', ascending=False)

largestFlower = sortedLargeFlowers.head(1)
largestFlower

,sepal_length,sepal_width,petal_length,petal_width,sepal_area,petal_area
131,7.9,3.8,6.4,2.0,30.02,12.8

In [43]:
areaofLargestflower = sortedLargeFlowers['sepal_area'].max()    #SNAS: to find the maximum value within column 'sepal_area' column
areaofLargestflower

np.float64(30.02)

In [44]:
areaofLargestflower2 = sortedLargeFlowers['sepal_area'].min()   #SNAS: to find the minimum value within column 'sepal_area' column
areaofLargestflower2

np.float64(15.040000000000001)