**05/12/2025**

Data:
- Qualitative
    - things and their attributes

- Quantitative
    - sizes of quantities

- Tables, something like columns,
    - row

In [26]:
#SNAS: find the mean

nums = [50, 47, 51, 49, 47]

mean = sum(nums) / len(nums)
print(mean)

48.8

In [ ]:
#SNAS: find median
#SNAS: First, sort the numbers. Second, targeted the middle number
#SNAS: my answer as below

import statistics

set1 = sorted([5, 50, 20, 80, 130])
print(set1)

median = statistics.median(set1)
print(f'Median is {median}')

[5, 20, 50, 80, 130]
Median is 50

In [29]:
#SNAS: below syntax for sorting in Python
nums = [20,80,130,50,89,90]
nums.sort()
print('sorted list nums: ', nums)

if len(nums)%2 == 0:
    # if length is even
    median = (nums[len(nums)//2] + nums[(len(nums)//2)-1]) / 2
    print(median)
else:
    # if the nums is odd, length/2
    #3/2 = 1.5 #3 is divided half
    #7/2 = 3.5  #7 is divided by half
    median = nums[len(nums)//2]
    print(median)

sorted list nums:  [20, 50, 80, 89, 90, 130]
84.5

In [33]:
import pandas as pd

iris = pd.read_csv('C:\\Users\\user\\Desktop\\AI & ML Class\\Daily-Practice\\Day 7-Pandas\\iris.csv')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [37]:
# aggregate

df = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
print('the mean is: ', df.mean())
print('the median is: ', df.median())
print('the mode is: ', df.mode())

the mean is:  sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64
the median is:  sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64
the mode is:     sepal_length  sepal_width  petal_length  petal_width
0           5.0          3.0           1.5          0.2

In [ ]:
sl = iris[['sepal_length']]
print('The mode is: ', sl.mode())   #SNAS: value that has the most frequent. this 'mode' function under pandas library

the mode is:     sepal_length
0           5.0

In [ ]:
x = {
    'a' : [1,2,3,4,5,6,7,8],
    'b' : [3,3,3,4,5,5,5,6]
}
xdf = pd.DataFrame(x)
xdf.head()

xdf['b'].mode()[0]
xdf['b'].mode()[1]

0    3
1    5
Name: b, dtype: int64

In [ ]:
xdf['b'].mode() #SNAS: finding the most frequent elements inside 'b' column

0    5
Name: b, dtype: int64

In [ ]:
xdf['b'].std()  # standard variation
xdf['b'].var()  #SNAS: how many variant in the list
xdf['b'].count()
xdf.count() #SNAS: how many row for each columns

In [42]:
df.describe()   #SNAS: give you all the statistics related to out dataset

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

- Spread of Data

- variance
- standard deviation

find mean
variance = [ ((data1-mean)**2) + ((data1-mean)**2) + ((data1-mean)**2) ] ... / 5

In [ ]:
# Exercise. My answer as below

class1 = [50,47,51,49,47]
class2 = [5,20,50,80,130]

c1 = pd.DataFrame(class1)
c2 = pd.DataFrame(class2)

print('The mean for Class 1 is: ', c1.mean())
print('The variance for Class 1 is: ', c1.var())

print('The mean for Class 2 is: ', c2.mean())
print('The variance for Class 2 is: ', c2.var())

The mean for Class 1 is:  0    48.8
dtype: float64
The variance for Class 1 is:  0    3.2
dtype: float64
The mean for Class 2 is:  0    57.0
dtype: float64
The variance for Class 2 is:  0    2495.0
dtype: float64

In [ ]:
import numpy as np

class1 = np.array([50,47,51,49,47])
class2 = np.array([5,20,50,80,130])

c1 = pd.DataFrame(class1)
c2 = pd.DataFrame(class2)

print('The mean for Class 1 is: ', c1.mean())
print('The variance for Class 1 is: ', c1.var())

print('The mean for Class 2 is: ', c2.mean())
print('The variance for Class 2 is: ', c2.var())

#SNAS: variance of class2 is sample variance

The mean for Class 1 is:  0    48.8
dtype: float64
The variance for Class 1 is:  0    3.2
dtype: float64
The mean for Class 2 is:  0    57.0
dtype: float64
The variance for Class 2 is:  0    2495.0
dtype: float64

In [ ]:
# SNAS sir answer as below

In [52]:
import numpy as np

class1 = np.array([50,47,51,49,47])
class2 = np.array([5,20,50,80,130])

mean = sum(class1)/len(class1)
print('Mean is: ', mean)

sumofdifference = np.array([((class1 - mean)**2)])
variance = (sumofdifference.sum())/len(class1)
print('The variance is: ',variance)

Mean is:  48.8
The variance is:  2.5599999999999996

In [ ]:
mean = sum(class2)/len(class2)
print('Mean is: ', mean)

sumofdifference = np.array([((class2 - mean)**2)])
variance = (sumofdifference.sum())/len(class2)
print('The variance of Class 2 is: ',variance)

#SNAS: variance of class2 is population variance produce by this syntax

Mean is:  57.0
The variance is:  1996.0

In [61]:
#SNAS: another way of writing above syntax

class1 = np.array([50,47,51,49,47])
class2 = np.array([5,20,50,80,130])

mean = sum(class1)/len(class1)
print('Mean is: ', mean)

variance = sum((class1 - mean)**2)/len(class1)
print('The variance is: ',variance)

Mean is:  48.8
The variance is:  2.5599999999999996

In [62]:
d = np.array([50,47,51,49,47]) - mean 
e = d **2

sum(e)/5

np.float64(2.5599999999999996)

In [63]:
variance1 = sum((class1 - mean)**2)/len(class1)
print('The variance1 is: ',variance1)

variance2 = sum((class2 - mean)**2)/len(class2)
print('The variance2 is: ',variance2)

The variance1 is:  2.5599999999999996
The variance2 is:  2063.2400000000002

In [64]:
std1 = variance1**0.5
std2 = variance2**0.5

print(std1, std2)

1.5999999999999999 45.42290171268234

**Assignment for Week 2**

**Explore how to sort a list manually**

Create a program, that takes a list, and return a sorted list
- only allowed to google, when you have struggled for atleast 1 hour
- if use google, create a different program, based on the same - understand the program
- you are not allowed to use list methods or libraries
- can use list, but not methods
- you can use numpy but not the methods like sort
- bonus points for finding algorithmn to sort

In [ ]:
nums = [20,80,130,50,89,90,50,31,67,3]

def to_sort(nums):

    nums_length = len(nums)     #SNAS: first, to find the length of the arguments in the list

    for i in range(nums_length):
        smallest_num = i        #SNAS: try to create a placement to hold the smallest number in the list
        
        for j in range(i + 1, nums_length):     #SNAS: the next number in the range
            if nums[j] < nums[smallest_num]:    #SNAS: if the next number is smaller than the smallest number, assigned it that place. compares values using indexes
                smallest_num = j
        #SNAS: 

        nums[i], nums[smallest_num] = nums[smallest_num], nums[i]   #SNAS: swap the numbers

    return nums

sorted_nums = to_sort(nums)
print(f'The sorted list is: ', sorted_nums)

The sorted list is:  [3, 20, 31, 50, 50, 67, 80, 89, 90, 130]

In [ ]:
nums = [20,80,130,50,89,90,50,31,67,3]

i = 0   #SNAS: first, indicate first index 0 is the smallest number
while i < len(nums):    #SNAS:  while the loop is still within the length of the list
    min_index = i   #SNAS: indicate the smallest number as initial number

    j = i + 1   #SNAS: increase the index position
    while j < len(nums):    #SNAS: while the increased loop is still within the list length
        if nums[j] < nums[min_index]:   #SNAS: compare the value at increased index with the value at current index
            min_index = j   #SNAS: if value at increased index is smaller than the value at the current index, update the numbervalue at that current index with increased index
        j += 1 #SNAS: continue loop at the next index

    #SNAS: swap the smallest value found with nums[i]
    nums[i], nums[min_index] = nums[min_index], nums[i]

    i += 1  #SNAS: outer loop, move to the next index

print(f'The sorted list is: ', nums)

The sorted list is:  [3, 20, 31, 50, 50, 67, 80, 89, 90, 130]

In [1]:
#SNAS: if using sort method as below

nums1 = [20,80,130,50,89,90,50,31,67,3]

nums1.sort()

print(f'The sorted list is: ', nums1)

The sorted list is:  [3, 20, 31, 50, 50, 67, 80, 89, 90, 130]

Variance

standard deviation

- spread of the data
-